apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: customapp
  annotations:
    description: this is test annotation
  name: mypod
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
